name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
 test:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1.9.0
        with:
          otp-version: "23.2"
          gleam-version: "0.20.0-rc1"
      - run: bin/migrate.sh gleam_todomvc_test
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
